using DomainLayer.Entities;
using Microsoft.EntityFrameworkCore;


namespace DataAccessLayer.DbContextFolder
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<UserDomain>(entity =>
            {
                entity.HasKey(e => e.Id);

                // Assuming Id is a GUID and generated by the database
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                // Configuring EmailAddress
                entity.Property(e => e.EmailAddress)
                      .IsRequired()
                      .HasMaxLength(100); // Set a max length for the email address

                // Ensuring EmailAddress is unique
                entity.HasIndex(e => e.EmailAddress).IsUnique();

                // Configuring Username
                entity.Property(e => e.Username)
                      .IsRequired()
                      .HasMaxLength(50); // Set a max length for the username

                // Add configurations for other properties and relationships here
            });

            // Configure other entities
        }

        public DbSet<UserDomain> Users { get; set; }
    }
}
